language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: BeLRvPgvkqdpCSWRRmJDLM7d1vOMiOFHkRLmWlEqsG8AT4HFx/A0wxhXzzKRedxhf0bYsxcGFb5MMTL4gaH3vZaXCq0ym50tb/BjnpQH6GQRyTs+Hggdf9GLdx/F1lMZ/farEITbY/SaX7dcZnlfiy2Ivvxo7WQ+yLI9WWDBblPUDKhXy6/jguxVWxGqaooZj5OdL9LbVxtfczsg1U54AmKIr/id4QSNkO6gd0cQFCapkR2scdBNRtJJctjA0kU+o9TqtuCn2JmSxX+lekgHcvUpONtpes+b3I4acE5YhOav3OQ1GnSntAlSi2sOFqZk90PxaUzkXI5ECZVSMAO0ABAhEp/cIaQ1drADV+7asucZAaowxBpvHJ7qBnd7wRszcM9ywrth90LHnLfAspA3RqTNOTwrY7RHY+pheYeZPqq+UqwmCcDCXQ0pIhYg9FD2QL/owIrHp8M7gpUbOWCyg4IMudanxj5SipE7wZjw+4iUbG/VtmiSYIEnlLA1Wg+7wvUZ/ZYPAygkJPUxd/oie3U/5XRThXpMws+zVu2ZwvU6V6qmT5PuabcVvSjD9oAM1TemBHdIoRbNn3PHJJYJI36lxfcfggala/JB6N/dKogR+Q+OGH8M0elDEOd5uaVpNX3g96F8JIjR5CdHEUPDzI46AIFHGWFWVZLtZiki5jc=
app: safe-anchorage-59758
true:
  repo: mchinn614/blog-post
