language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: IENjcs+it/NQJdMNKsxAPfFD+HKtMyfBJFQNcqhFDlJyvaWvrCZyuvNxB3ae8haAYGJj4CJOwBiKAqBhHoi13KzPypM+Vif/xm3A172+Xz8MyofLTa5u7pfQviFehRVcf9FcPo+g1AOaFhunXBbxEDKDXsYqb5mEYxZE55ujvNy74JoeitqqMdigAeWt56+tqjXtpaISpj9uZ5p51zKo36o4JzmmYnPWRtwkWgKm2/+1n3CbYr75XcV85S1pMdB+QfZMCHl2O5WeEOFrQAu7R5KZb0La9waNp1IlqGNi+VrqwAF6cgK6kUO676G9K9YOJyhLW4zLFKvVBWagxeB2cKKIs4qSmNAVt8alnweX1Xh2fE4t4VEtcMpcx7isoY52gJOM5UNaq42f/PThYF5o1p0T54HU6K5wqXEHujfj5zyuPOU7RVXz+AITUSUnB+k4CwWVdMQ8RaXYOXq0+JCNiKPozfE6DpdlVnB6V3F1cWOGitJ8v7pImCk2GEsmJjrRxn9xmF7dbv7dM38WoOR/gpxRrTvyr6fo64S2NxTVrjNgYeANqb0AMPVTxtU36Ue29okPqiTiBG8he9ABtb92q14jeuPLL5ZdDPqdr4EgIpKBJy+q6wE68H/fbg8B3qYvtXUAfXEvayiE7HETtytz0Z0Ij+fsejAL6IZSBggZKHk=
